spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  data:
    jpa:
      repositories:
        enabled: true #配置Repository是否生效，默认为true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
#rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh