spring:
  profiles:
    active: dev

---
eureka:
  client:
    register-with-eureka: false #不注册到eureka
    fetch-registry: false #不从eureka发现服务
  server:
    enable-self-preservation: false
spring:
  profiles: dev #开发环境
  application:
    name: spring-cloud-eureka

---
eureka:
  client:
    register-with-eureka: false #不注册到eureka
    fetch-registry: false #不从eureka发现服务
  server:
    enable-self-preservation: true
spring:
  profiles: prod #开发环境
  application:
    name: spring-cloud-eureka