spring:
  profiles:
    active: dev
server:
  port: 6001

eureka:
  instance: 
    hostname: eureka6001.com
---
eureka:
  client:
    register-with-eureka: false #不注册到eureka
    fetch-registry: false #不从eureka发现服务
    service-url:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false
spring:
  profiles: dev #开发环境
  application:
    name: spring-cloud-eureka
#rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
eureka:
  client:
    register-with-eureka: false #不注册到eureka
    fetch-registry: false #不从eureka发现服务
    service-url:
     defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: true
spring:
  profiles: prod #开发环境
  application:
    name: spring-cloud-eureka
#rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh